# version: '3.8'

services:
    app:
        build:
            args:
                user: 1000
                uid: 1000
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www/html
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/logs/php/php-fpm.log:/var/log/fpm-php.www.log
        ports:
            - "9000:9000"
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        networks:
            - myhealth-network
        depends_on:
            # - meilisearch
            - redis

    nginx:
        image: nginx:latest
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./docker/nginx/:/etc/nginx/conf.d/
            - .:/var/www/html
            - ./docker/logs/nginx:/var/log/nginx/
        depends_on:
            - app
        networks:
            - myhealth-network

    # mysql:
    #     image: mysql:8.0
    #     container_name: mysql
    #     restart: unless-stopped
    #     environment:
    #         MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_ROOT_HOST: '%'
    #         MYSQL_DATABASE: '${DB_DATABASE}'
    #         MYSQL_USER: '${DB_USERNAME}'
    #         MYSQL_PASSWORD: '${DB_PASSWORD}'
    #         # MYSQL_TCP_PORT: '${DB_PORT}'
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #         SERVICE_TAGS: dev
    #         SERVICE_NAME: mysql
    #     ports:
    #         - '${FORWARD_DB_PORT:-3306}:3306'
    #     volumes:
    #         - './docker-mysql:/var/lib/mysql'
    #         - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    #     networks:
    #         - myhealth-network
    #     healthcheck:
    #         test:
    #             - CMD
    #             - mysqladmin
    #             - ping
    #             - '-p${DB_PASSWORD}'
    #         retries: 3
    #         timeout: 5s

    redis:
        image: 'redis:alpine'
        container_name: redis
        ports:
            - '${REDIS_FORWARD_PORT:-6379}:6379'
        volumes:
            - './docker-redis:/data'
        networks:
            - myhealth-network
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    # pma:
    #     image: phpmyadmin
    #     container_name: pma
    #     restart: always
    #     links:
    #         - mysql
    #     ports:
    #         - 8080:80
    #     environment:
    #         PMA_ARBITRARY: 1
    #         PMA_HOST: ${DB_HOST}
    #         PMA_PORT: ${DB_PORT}
    #         MAX_EXECUTION_TIME: 600
    #         MEMORY_LIMIT: 1024M
    #         UPLOAD_LIMIT: 300M
    #     networks:
    #         - myhealth-network

    # meilisearch:
    #     image: getmeili/meilisearch:latest
    #     container_name: meili
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     environment:
    #         MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    #     volumes:
    #         - 'docker-meilisearch:/meili_data'
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://localhost:7700/health'
    #         retries: 3
    #         timeout: 5s
    #     networks:
    #         - myhealth-network

networks:
    myhealth-network:
        driver: bridge

volumes:
    docker-redis:
        driver: local
    # docker-mysql:
    #     driver: local
    # docker-meilisearch:
    #     driver: local
